"""add notes column

Revision ID: 42feb9574f23
Revises: 640a2f76dbcf
Create Date: 2024-01-17 14:51:44.214623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42feb9574f23'
down_revision: Union[str, None] = '640a2f76dbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'notes')
    # ### end Alembic commands ###
