"""auto-profiles

Revision ID: 640a2f76dbcf
Revises: 714236ab8965
Create Date: 2024-01-17 14:48:54.439039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640a2f76dbcf'
down_revision: Union[str, None] = '714236ab8965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('applications', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('applications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
